FROM node:20 AS build

WORKDIR /app

COPY package.json /app

RUN npm install

COPY . /app

FROM node:20-slim

WORKDIR /app

RUN apt-get update && apt-get install -y sqlite3

COPY --from=build /app /app

RUN npm install --production && npm rebuild sqlite3

EXPOSE 3000

CMD ["node", "index.js"]